### ISSUE TITLE
Is InterFaceGAN;s face editing is prior than styleCariGAN in paper?

### ISSUE THREAD

**Issue by lizekui** [wonjongg/StyleCariGAN#10]
Firstly, this work is damn fascinating! Admiring you all! Thanks!

I am a beginner of GAN, and I wonder know a naive question, Is InterFaceGAN's face editing is prior than styleCariGAN in paper?

For example, if I understand correctly, I want to draw an open-mouth face caricature from a close-mouth photo, I need to edit face firstly using some GAN like InterFaceGAN, and then use the prior output image, send as input to styleCariGAN?

I test styleCariGAN's xx.pt invert codes seems not compatible with InterFaceGAN's xx.npy format, couldn't edit after style-cari processing directly. haha

**Comment by ycjungSubhuman** [comment]
Sorry for late reply. Our StyleCariGAN framework is an augmented StyleGAN. InterFaceGAN is an editing in latent space of StyleGAN. InterFaceGAN on StyleCariGAN applies editing on the latent space on the StyleGAN. Our feature modulation blocks attached to the StyleGAN render the edited latent code into a caricature. I hope this helps your understanding.
