### ISSUE TITLE
Is there a way to generate clothes style mapping the cari avatar?

### ISSUE THREAD

**Issue by lizekui** [wonjongg/StyleCariGAN#13]
Hi this work is fantastic! 

I wonder know, is there a way to generate clothes style mapping the cari avatar?

For example, the man wears a suit, our model generates the full body portrait in cari style.

Thanks first!

**Comment by ycjungSubhuman** [comment]
Achieving that goal seems non-trivial. I believe you may first start by changing the dataset from (regular face, caricature face) dataset to (full body photo, full body caricature). However, it seems challenging because full body caricature dataset is not easy to define and gather.
