### ISSUE TITLE
Error occurs when testing on my aligned face images!!!

### ISSUE THREAD

**Issue by neverbiasu** [wonjongg/StyleCariGAN#18]
I meet this mistake when I try your test.py by our images. 
![image](https://github.com/wonjongg/StyleCariGAN/assets/90372299/b2f02e32-3e25-4282-a925-75218c69f779)
I guess if it because we don't have the args.image_name+'.pt' in our images folder.
and it occurs
![image](https://github.com/wonjongg/StyleCariGAN/assets/90372299/fac2d539-dd54-4ccd-8d03-37c920f7b616)
by the way, our environment is suitable for this project. running on 2080ti + cuda10.1 + torch 1.5.1

Need I train a model myself or where could I get the pt for each images in my folder.

**Comment by wonjongg** [comment]
To analyze the first error, could you share your directory structure? and please verify that your image files are correctly visible when using an image viewer.

For the second issue, if you set the flag "--invert_images", then you can obtain {filename}.pt automatically. Please set the flag if you don't have *.pt files. Also, our current version doesn't support 1024x1024 resolution images. Please don't set the "--size" to 1024.
