### ISSUE TITLE
How to generate caricatures from images

### ISSUE THREAD

**Issue by vonurkilinc** [wonjongg/StyleCariGAN#19]
I dont understand how am i suppose to generate caricature from input photos.
I downloaded the checkpoint "001000.pt" 

When I run 
test.py --invert_images --ckpt checkpoint/StyleCariGAN/001000.pt

I get the error: RuntimeError: File samples/samples\jeniffer256.pt cannot be opened.  

Am I somehow suppose to generate .pt files for each of my Images.

**Comment by wonjongg** [comment]
Please check the forward and backward slashes. The slash for file path should be properly set according to your OS.

**Comment by vonurkilinc** [comment]
Thank you but  I want to use your weights to create a caricature of a image I provide. How can I achieve this.
For each Image it asks for a pt file named imagename.pt how do I create these files if I need them.
