### ISSUE TITLE
Model is missing from ./download.sh

### ISSUE THREAD

**Issue by DenisSergeevitch** [wonjongg/StyleCariGAN#2]
Hello, file https://www.dropbox.com/s/ryc7v1ghsm54mr8/001000.pt?dl=0 is not available anymore. Please, reupload it.

**Comment by ycjungSubhuman** [comment]
Hi DenisSergeevitch. Thanks for filing the issue. We are working on this problem. In the meantime, you can download the checkpoint from here temporarily: https://drive.google.com/file/d/1hBAWJQjbB-B_EA2xsz1XGUh6gDNb-GKO/view?usp=sharing

**Comment by virtualramblas** [comment]
Trying to download the checkpoint within a Colab notebook using gdown I get the following error:
_Permission denied: https://drive.google.com/uc?id=1hBAWJQjbB-B_EA2xsz1XGUh6gDNb-GKO
Maybe you need to change permission over 'Anyone with the link'?_
By manually downloading the checkpoint everything is fine.

**Comment by ycjungSubhuman** [comment]
> It seems the number of downloads is causing the permission problem. Google drive sometimes blocks download when too much downloads are happening. @wonjongg will soon resolve the issue and make the download smoother.
> Trying to download the checkpoint within a Colab notebook using gdown I get the following error:
> _Permission denied: https://drive.google.com/uc?id=1hBAWJQjbB-B_EA2xsz1XGUh6gDNb-GKO Maybe you need to change permission over 'Anyone with the link'?_
> By manually downloading the checkpoint everything is fine.

It seems Google Drive blocks automated requests when multiple download requests occur in a short time slot. The permission itself is correctly set. @wonjongg will soon resolve the download issue and make the process smooth.

**Comment by ycjungSubhuman** [comment]
Now the download link in `download.sh` will work fine. Closing.
