### ISSUE TITLE
Colab version

### ISSUE THREAD

**Issue by DenisSergeevitch** [wonjongg/StyleCariGAN#3]
Here is colab version if anyone wants to try it:
https://colab.research.google.com/drive/1HDRQGm7pvC9mAb6Lktoft_SmY9sCq_Qg?usp=sharing

**Comment by AK391** [comment]
@DenisSergeevitch thanks do you know if it can be run on cpu in colab?

**Comment by ycjungSubhuman** [comment]
Note that this Colab version is not officially supported. The gdown part may cause error due to high download requests.
