### ISSUE TITLE
pre-trained model weights download problem

### ISSUE THREAD

**Issue by cjcandxy** [wonjongg/StyleCariGAN#4]
why I can't download pre-trained model weights

**Comment by ycjungSubhuman** [comment]
> why I can't download pre-trained model weights

Could you describe what you did to download the weights? Also, could you attach corresponding error message?
Running `bash download.sh` should work

**Comment by cjcandxy** [comment]
thanks，i have solve this problem,just because a small detail

**Comment by ycjungSubhuman** [comment]
No problem. Closing.
