### ISSUE TITLE
Pretrained model Caricature StyleGan2

### ISSUE THREAD

**Issue by TorRient** [wonjongg/StyleCariGAN#8]
hi @wonjongg, your work is interesting!
Can you share with me the pre-trained model Caricature StyleGan2 fine-tuned on the caricature dataset (WebCaricature)?
Thank you!

**Comment by wonjongg** [comment]
You can download the pre-trained model for the WebCaricature dataset:
https://www.dropbox.com/s/8ycqr0sy8zah6h5/120000.pt?dl=0

Thank you for your interest in our project! 😄
