### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by AK391** [wonjongg/StyleCariGAN#9]
please add a google colab for inference

**Comment by HanClinto** [comment]
@AK391 An unofficial Colab was posted here: https://colab.research.google.com/drive/1HDRQGm7pvC9mAb6Lktoft_SmY9sCq_Qg?usp=sharing

**Comment by ycjungSubhuman** [comment]
> @AK391 An unofficial Colab was posted here: https://colab.research.google.com/drive/1HDRQGm7pvC9mAb6Lktoft_SmY9sCq_Qg?usp=sharing

Thanks. Btw, in that colab code, change 

```
!gdown https://drive.google.com/u/0/uc?id=1cA1sob3obHXMcP_I2kIDMVOV_F6zwD34&export=download
```
into 

```
bash download.sh
```

then the unofficial Colab code should work fine.

**Comment by amrzv** [comment]
> > @AK391 An unofficial Colab was posted here: https://colab.research.google.com/drive/1HDRQGm7pvC9mAb6Lktoft_SmY9sCq_Qg?usp=sharing
> 
> Thanks. Btw, in that colab code, change
> 
> ```
> !gdown https://drive.google.com/u/0/uc?id=1cA1sob3obHXMcP_I2kIDMVOV_F6zwD34&export=download
> ```
> 
> into
> 
> ```
> bash download.sh
> ```
> 
> then the unofficial Colab code should work fine.

@DenisSergeevitch
Now, the last cell should be:
```
%cd /content/StyleCariGAN/
!python test.py --ckpt 001000.pt --input_dir examples/samples --output_dir /content/drive/MyDrive/Caricature --invert_images
```

**Comment by DenisSergeevitch** [comment]
@amrzv updated, thanx

**Comment by amrzv** [comment]
> @amrzv updated, thanx

@DenisSergeevitch 
Seems, previous cell changed too, and now checkpoint path in last cell became wrong.
So, depending on previous cell:
```
%cd /content/StyleCariGAN/
!bash ./download.sh

%cd /content/StyleCariGAN/
!python test.py --ckpt checkpoint/StyleCariGAN/001000.pt --input_dir examples/samples --output_dir /content/drive/MyDrive/Caricature --invert_images
```
or
```
%cd /content/StyleCariGAN/
!gdown https://drive.google.com/u/0/uc?id=1cA1sob3obHXMcP_I2kIDMVOV_F6zwD34&export=download

%cd /content/StyleCariGAN/
!python test.py --ckpt 001000.pt --input_dir examples/samples --output_dir /content/drive/MyDrive/Caricature --invert_images
```

P.S: more prettified usage of gdown
`!gdown --id 1cA1sob3obHXMcP_I2kIDMVOV_F6zwD34`
